name: GDDML
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - alsa-lib=1.2.7.2
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - certifi=2022.12.7
  - contourpy=1.0.5
  - cycler=0.11.0
  - expat=2.4.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.37.4
  - freetype=2.12.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - greenlet=1.1.3
  - harfbuzz=5.2.0
  - icu=70.1
  - joblib=1.2.0
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcups=2.3.3
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.74.0
  - libgomp=12.1.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.38
  - libsqlite=3.39.4
  - libstdcxx-ng=12.1.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxgboost=1.6.2
  - libxml2=2.10.2
  - libzlib=1.2.12
  - matplotlib-base=3.6.0
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=3.0
  - numpy=1.23.3
  - openbabel=3.1.1
  - openjdk=17.0.3
  - openjpeg=2.5.0
  - openssl=3.1.0
  - packaging=21.3
  - padelpy=0.1.12
  - pandas=1.5.0
  - pcre2=10.37
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-xgboost=1.6.2
  - pycairo=1.21.0
  - pyparsing=3.0.9
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.4
  - rdkit=2022.03.5
  - readline=8.1.2
  - reportlab=3.5.68
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - setuptools=65.4.1
  - six=1.16.0
  - sqlalchemy=1.4.41
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tzdata=2022d
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xgboost=1.6.2
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyz2mol=0.1.2
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.5.2

